[package]
name = "mb-arith"
version = "0.1.0"
edition = "2021"
authors = ["Bill Wood <wpwoodjr@gmail.com>"]

[dependencies]
num = "*"
rayon = "*"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
