apiVersion: v1
kind: Service
metadata:
  name: mandelbrot
  namespace: mandelbrot # {"$kpt-set":"namespace"}
spec:
  selector:
    app: mandelbrot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandelbrot
  namespace: mandelbrot # {"$kpt-set":"namespace"}
spec:
  selector:
    matchLabels:
      app: mandelbrot
  replicas: 4 # {"$kpt-set":"replicas"}
  template:
    metadata:
      labels:
        app: mandelbrot
    spec:
      containers:
      - name: mandelbrot
        image: wpwoodjr/mandelbrot:latest # {"$kpt-set":"image"}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
          # imagePullSecrets:
          # - name: mandelbrot
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mandelbrot
  namespace: mandelbrot # {"$kpt-set":"namespace"}
spec:
  rules:
  - host: mb.localhost # {"$kpt-set":"url"}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mandelbrot
            port:
              number: 8080
  tls:
  - hosts:
    - mb.localhost # {"$kpt-set":"url"}
