apiVersion: v1
kind: Service
metadata:
  name: mandelbrot
  namespace: mandelbrot # {"$kpt-set":"namespace"}
spec:
  selector:
    app: mandelbrot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandelbrot
  namespace: mandelbrot # {"$kpt-set":"namespace"}
spec:
  selector:
    matchLabels:
      app: mandelbrot
  replicas: 4 # {"$kpt-set":"replicas"}
  template:
    metadata:
      labels:
        app: mandelbrot
    spec:
      containers:
      - name: mandelbrot
        image: harbor.gsk.com/sdi/mandelbrot:latest # {"$kpt-set":"image"}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
          # imagePullSecrets:
          # - name: mandelbrot
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mandelbrot
  namespace: mandelbrot # {"$kpt-set":"namespace"}
spec:
  rules:
  - host: mandelbrot.devk8s.gsk.com # {"$kpt-set":"url"}
    http:
      paths:
      - backend:
          serviceName: mandelbrot
          servicePort: 8080
  tls:
  - hosts:
    - mandelbrot.devk8s.gsk.com # {"$kpt-set":"url"}
