---
swagger: "2.0"
info:
  description: "Does Mandelbrot computation"
  version: "1.0.0"
  title: "Mandelbrot"
  termsOfService: "https://www.gsk.com/en-gb/terms-of-use/"
  contact:
    email: "william.wood@gsk.com"
host: "localhost:8080"
basePath: "/v1"
schemes:
- "http"
paths:
  /mandelbrot/compute:
    post:
      tags:
      - "mandelbrot"
      summary: "Iterate over pixels to determine if each is in the Mandelbrot set"
      description: ""
      operationId: "computeMandelbrot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "mandelbrotCoords"
        description: "Mandelbrot coordinates to compute"
        required: true
        schema:
          $ref: "#/definitions/MandelbrotCoords"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/MandelbrotResults"
        400:
          description: "Client Error"
          schema:
            $ref: "#/definitions/ApiFailureResponse"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ApiFailureResponse"
      x-swagger-router-controller: "Mandelbrot"
definitions:
  MandelbrotCoords:
    type: "object"
    required:
    - "columns"
    - "dx"
    - "maxIterations"
    - "xmin"
    - "y"
    properties:
      y:
        type: "number"
        format: "f64"
      xmin:
        type: "number"
        format: "f64"
      dx:
        type: "number"
        format: "f64"
      columns:
        type: "integer"
        format: "int32"
      maxIterations:
        type: "integer"
        format: "int32"
    example:
      xmin: -2.20000000000000017763568394002504646778106689453125
      maxIterations: 100
      dx: 0.1499999999999999944488848768742172978818416595458984375
      columns: 20
      y: -0.59999999999999997779553950749686919152736663818359375
  MandelbrotResults:
    type: "array"
    items:
      type: "integer"
      format: "int32"
  ApiFailureResponse:
    type: "object"
    properties:
      message:
        type: "string"
        enum:
        - "CLIENT ERROR"
        - "SERVER ERROR"
externalDocs:
  description: "GSK Software Engineering Careers"
  url: "https://www.gsk.com/en-gb/careers/careers-search/?q=software%20engineer"
