apiVersion: v1
kind: Service
metadata:
  name: mandelbrot
spec:
  selector:
    app: mandelbrot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8081
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandelbrot
spec:
  selector:
    matchLabels:
      app: mandelbrot
  replicas: 4
  template:
    metadata:
      labels:
        app: mandelbrot
    spec:
      containers:
        - name: mandelbrot
          image: harbor.gsk.com/sdi/mandelbrot-dev:tag
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
      # imagePullSecrets:
      # - name: mandelbrot
