apiVersion: v1
kind: Service
metadata:
  namespace: akstechopstestenv-devtest
  name: mandelbrot
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: mandelbrot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
#    nodePort: null
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: akstechopstestenv-devtest
  name: mandelbrot
spec:
  selector:
    matchLabels:
      app: mandelbrot
  replicas: 24
  template:
    metadata:
      labels:
        app: mandelbrot
    spec:
      containers:
        - name: mandelbrot
          image: wpwoodjr/mandelbrot:3.3.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
