apiVersion: v1
kind: Namespace
metadata:
  name: mandelbrot
---
apiVersion: v1
kind: Service
metadata:
  namespace: mandelbrot
  name: mandelbrot

spec:
  selector:
    app: mandelbrot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mandelbrot
  name: mandelbrot
spec:
  selector:
    matchLabels:
      app: mandelbrot
  replicas: 2
  template:
    metadata:
      labels:
        app: mandelbrot
    spec:
      containers:
        - name: mandelbrot
          image: harbor.gsk.com/sdi/mandelbrot-dev:3.3.4
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
      # imagePullSecrets:
      # - name: mandelbrot
