apiVersion: v1
kind: Service
metadata:
  name: mandelbrot
spec:
  selector:
    app: mandelbrot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandelbrot
spec:
  selector:
    matchLabels:
      app: mandelbrot
  replicas: 12
  template:
    metadata:
      labels:
        app: mandelbrot
    spec:
      containers:
        - name: mandelbrot
          image: harbor.gsk.com/sdi/mandelbrot-dev:tag
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
      # imagePullSecrets:
      # - name: mandelbrot
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mandelbrot
spec:
  rules:
  - host: mandelbrot.gsk.com
    http:
      paths:
      - backend:
          serviceName: mandelbrot
          servicePort: 8080

  tls:
  - hosts:
    - mandelbrot.gsk.com
